### ISSUE TITLE
Erreur liée au double // en fin d'URL

### ISSUE THREAD

**Issue by Hipjea** [LUniversiteNumerique/parcours-hybridation#121]
@AlysonKocher le lien `https://www.fun-mooc.fr/fr/cours/la-sculpture-grecque-dalexandre-a-cleopatre-partie-ii//` donne une erreur 404, je pense que ce devrait être : `https://www.fun-mooc.fr/fr/cours/la-sculpture-grecque-dalexandre-a-cleopatre-partie-ii/` 

https://github.com/LUniversiteNumerique/parcours-hybridation/blob/b5ac9f4998c4a17d470ebdc88172e97f627c6217/arts-lettres-et-langues/37-licence-mention-arts.yml#L97

**Comment by AlysonKocher** [comment]
Il me semble que j'ai réglé ces erreurs dans mon précédent envoie non ?

**Comment by Hipjea** [comment]
Oui, a priori tu l'as corrigé, c'est en attente de la validation du pull request à venir.
