### ISSUE TITLE
Texte "langues étrangères" non cliquable dans les compétences transversales

### ISSUE THREAD

**Issue by NicolasBrosse** [LUniversiteNumerique/parcours-hybridation#64]
Sur le bac à sable, lorsque l'on sélectionne la thématique "compétences transversales", le texte "langues étrangères" n'est pas cliquable et donc la fenêtre modale n'apparaît pas.

Je pense à un formatage incorrect dans `competences-transversales/43-langues-etrangeres.yml` mais peut me tromper et n'ai rien remarqué.

**Comment by Hipjea** [comment]
Oui, c'est déjà signalé à @AlysonKocher pour correction
